import numpy as np

categories = [np.array(['GP', 'MS'], dtype=object),
                np.array(['F', 'M'], dtype=object),
                np.array(np.arange(10, 30, 1), dtype=object),
                np.array(['R', 'U'], dtype=object),
                np.array(['GT3', 'LE3'], dtype=object),
                np.array(['A', 'T'], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['course', 'home', 'other', 'reputation'], dtype=object),
                np.array(['father', 'mother', 'other'], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array(np.arange(0, 100, 1),
                dtype=object)]

categories2 = [np.array(['GP', 'MS'], dtype=object),
                np.array(['F', 'M'], dtype=object),
                np.array(np.arange(10, 30, 1), dtype=object),
                np.array(['R', 'U'], dtype=object),
                np.array(['GT3', 'LE3'], dtype=object),
                np.array(['A', 'T'], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['course', 'home', 'other', 'reputation'], dtype=object),
                np.array(['father', 'mother', 'other'], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array(np.arange(0, 100, 1),
                   dtype=object),
                np.array(np.arange(0, 20, 1),
                   dtype=object),
                np.array(np.arange(0, 20, 1),
                   dtype=object),
                np.array([0, 1], dtype=object)]

categories3 = [np.array(['GP', 'MS'], dtype=object),
                np.array(['F', 'M'], dtype=object),
                np.array(np.arange(10, 30, 1), dtype=object),
                np.array(['R', 'U'], dtype=object),
                np.array(['GT3', 'LE3'], dtype=object),
                np.array(['A', 'T'], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3, 4], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
                np.array(['course', 'home', 'other', 'reputation'], dtype=object),
                np.array(['father', 'mother', 'other'], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([1, 2, 3, 4], dtype=object),
                np.array([0, 1, 2, 3], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array(['no', 'yes'], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array([1, 2, 3, 4, 5], dtype=object),
                np.array(np.arange(0, 100, 1),
                   dtype=object),
                np.array(np.arange(0, 20, 1),
                   dtype=object)]
